jobs:
- job: build_and_test
  pool:
    vmImage: ubuntu-20.04
  steps:
  - script: ./app.sh build test-container
    displayName: 'Build docker image'

  - script: ./app.sh test test-container
    displayName: 'Test docker image'

- job: build_and_release
  pool:
    vmImage: ubuntu-20.04
  steps:
  - script: ./app.sh build release-image
    displayName: 'Build docker image'
