jobs:
- job: build_and_test
  trigger:
    branches:
      include:
      - '*'
  pool:
    vmImage: ubuntu-20.04
  steps:
  - displayName: 'Build docker image'
    script: ./app.sh build test-container

  - displayName: 'Test docker image'
    script: ./app.sh test test-container

- job: build_and_release
  trigger:
    branches:
      include:
      - refs/tags/*
  pool:
    vmImage: ubuntu-20.04
  steps:
  - displayName: 'Build docker image'
    script: ./app.sh build release-image
