trigger:
  tags:
    include:
    - v*

variables:
  - name: app_version
    value: beta

jobs:
- job: build_and_release
  pool:
    vmImage: ubuntu-20.04
  steps:
  - script: ./app.sh build ${{ variables.app_version }}
    displayName: 'Build docker image'

  - script: |
      docker login -u ${{ variables.DOCKER_USERNAME }} -p=${{variables.DOCKER_PASSWORD}}
      ./app.sh push ${{ variables.app_version }}

    displayName: 'Push docker image'