trigger:
  tags:
    include:
    - v*

variables:
  - name: app_version
    value: beta

jobs:
- job: build_and_release
  pool:
    vmImage: ubuntu-20.04
  steps:
  - script: ./app.sh build $(app_version)
    displayName: 'Build docker image'

  - script: |
      docker login -u $(DOCKER_USERNAME) -p=$(DOCKER_PASSWORD)
      ./app.sh push $(app_version)

    displayName: 'Push docker image'