trigger:
  tags:
    include:
    - v*

jobs:
- job: build_and_release
  pool:
    vmImage: ubuntu-20.04
  steps:
  - script: |
      latest_tag=$(git describe --tags --abbrev=0)
      echo "##vso[task.setvariable variable=app_version]$latest_tag"

    displayName: 'Find git tag'

  - script: ./app.sh build $(app_version)
    displayName: 'Build docker image'

  - script: |
      docker login -u $(DOCKER_USERNAME) -p=$(DOCKER_PASSWORD)
      ./app.sh push $(app_version)

    displayName: 'Push docker image'
