global_variable:
  app_version: test

trigger:
  branches:
    include:
    - master
pr:
  branches:
    include:
    - '*'

jobs:
- job: build_and_test
  pool:
    vmImage: ubuntu-20.04
  steps:
  - script: ./app.sh build ${app_version}
    displayName: 'Build docker image'

  - script: ./app.sh test ${app_version}
    displayName: 'Test docker image'
