variables:
  - name: app_version
    value: test

trigger:
  branches:
    include:
    - master
pr:
  branches:
    include:
    - '*'

jobs:
- job: build_and_test
  pool:
    vmImage: ubuntu-20.04
  steps:
  - script: ./app.sh build ${{ variables.app_version }}
    displayName: 'Build docker image'

  - script: ./app.sh test ${{ variables.app_version }}
    displayName: 'Test docker image'
