
name: Build

  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Check docker environment
        run: docker info

      - name: Test docker image
        run: ./app.sh build
